---
title: "Detalle de las Funciones"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Librerias Utilizadas para realizar el proyecto
library(shiny)
library(corrplot)
library(ggplot2)
library(factoextra)
library(DMwR)
library(lubridate)
library(dplyr)
setwd("TrabajoFinalAdminInfo_Cavero_Morales")
source("GeneralScript.R")

```

```{r}
#1) Nos muestra la cantidad de casos registrados en total, haciendo un filtro por año y por el tipo de modalidad de violencia.
    #df= dataframe a utilizar , anho= año el cual desea buscar , modalidad=Tipo de modalidad a buscar , totdatos= cantidad de datos a mostrar

casos_anhos_modalidad<-function(df,anho,modalidad,totdatos)
{
  if(totdatos==TRUE)
  {
  return(q1<-df%>%filter(year(df$fec_registro)==anho & df$MODALIDAD ==modalidad)%>%summarise(Total=n()))
  }
  else
  {
  return(q1<-df%>%filter(year(df$fec_registro)==anho & df$MODALIDAD ==modalidad)%>%group_by(MODALIDAD,fec_registro)%>%summarise(Total=n()))
  }
}  
q1<-casos_anhos_modalidad(datos_violencia,2017,"VIOLENCIA FISICA",FALSE)
```


```{r}
##Muestra de los Valores: 
q1

```

```{r}
#2) Nos muestra la cantidad de casos para cada tipo de modalidad que se encuentra en el dataset.
casos_totales_por_modalidad<-function(df)
{
  return(q2<-df%>%group_by(Modalidad=df$MODALIDAD)%>%summarise(Cantidad_Casos=n()))  
}
q2<-casos_totales_por_modalidad(datos_violencia)
#Muestra de Valores:
q2
```

```{r}
#3) Nos muestra  la cantidad de denuncias realizadas por cada departamento en el dataset.
#df : Es el dataframe que utilizaremos
group_by_denuncias<-function(df)
{
  return(df%>%group_by(DPTO_CIA)%>%summarise(Total=n())%>%arrange(desc(Total)))
}

q3<-group_by_denuncias(datos_violencia)
#Muestra de Valores:
q3

```

```{r}
#4) Nos muestra la cantidad de personas encontradas en el dataset correspondiente a su situación en la denuncia, donde podemos seleccionar ver todas las situaciones posibles o colocar el TOP con más cantidad de personas.
relacion_denuncia<-function(df,cant_top)
{
  q<-df%>%group_by(SIT_PERSONA)%>%summarise(Total=n())%>%arrange(desc(Total))
  if(cant_top==0)
  {
    return(q[,c(1,2)])
  }
  else{
    return(q[c(1:cant_top),c(1,2)])
    
  }
}

q4<-relacion_denuncia(datos_violencia,5)
#Muestra de Valores:
q4
```

```{r}
#5) Nos muestra la cantidad de casos registrados  según la nacionalidad del denunciante, donde podemos filtar para ver todos los paises o un top de los datos. 
cant_paises<-function(df,cant_top)
{
  q<-df%>%group_by(pais_natal)%>%summarise(Total=n())%>%arrange(desc(Total))
  if(cant_top==0)
  {
    return(q[,c(1,2)])
  }
  else{
  return(q[c(1:cant_top),c(1,2)])

  }
}

q5<-cant_paises(datos_violencia,0)
#Muestra de Valores:
q5
```


```{r}
#6 Nos muestra la cantidad de casos registrados en el dataset filtrando por la edad del denunciante.
casos_Edad<-function(df)
{
  return(df%>%group_by(EDAD)%>%summarise(Total=n())%>%arrange(desc(Total)))
}

q6<-casos_Edad(datos_violencia)
#Muestra de Valores:
q6
```

```{r}
#7 Nos muestra la cantidad de casos registrados en el dataset filtrando por el sexo del denunciante.

casos_sexo<-function(df)
{
  return(df%>%group_by(SEXO)%>%summarise(Total=n())%>%arrange(desc(Total)))
}
q7<-casos_sexo(datos_violencia)
#Muestra de Valores:
q7
```

```{r}
#8 Nos muestra la cantidad de casos registrados en el dataset filtrado por los distritos, asimismo te permite mostrar un Top distritos con más casos o mostrar todos los distritos completos.
casos_distritos<-function(df,cant_top)
{
  q<-df%>%group_by(DIST_CIA)%>%summarise(Total=n())%>%arrange(desc(Total))
  
  if(cant_top==0)
  {
    return(q[,c(1,2)])
  }
  else{
    return(q[c(1:cant_top),c(1,2)])
    
  }
}

q8<-casos_distritos(datos_violencia,5)
#Muestra de Valores:
q8

```

```{r}

#9 Nos muestra la cantidad de personas que fueron derivados a una Fiscalia en concreto, nos mostrara la cantidad de usuarios en cada Fiscalia.
fiscalias<-function(df)
{
  return(df%>%group_by(DERIVADA_FISCALIA)%>%filter(DERIVADA_FISCALIA!="NULL")%>%summarise(Total=n())%>%arrange(desc(Total)))
}
q9<-fiscalias(datos_violencia)
#Muestra de Valores:
q9

```

```{r}
#10 Nos muestra la cantidad de denunciantes y denunciados filtrado según el sexo de la persona.

situcion_persona_por_Sexo<-function(df)
{
  return(df%>%group_by(SIT_PERSONA,SEXO)%>%filter(SIT_PERSONA=="DENUNCIANTE" |SIT_PERSONA=="DENUNCIADO")%>%summarise(Total=n())%>%arrange(desc(Total)))
}
q10<-situcion_persona_por_Sexo(datos_violencia)
#Muestra de Valores:
q10
```

```{r}
#11 Nos muestra la cantidad de casos registrados en el dataset filtrado por el mes.

mayor_mes<-function(df)
{
  return(df%>%group_by(MES)%>%summarise(Total=n())%>%arrange(desc(Total)))
}

q11<-mayor_mes(datos_violencia)
#Muestra de Valores:
q11
```

```{r}
#12 Nos muestra la cantidad de casos registrados por el estado civil del denunciante.

estado_civil<-function(df)
{
  return(df%>%group_by(EST_CIVIL)%>%filter(EST_CIVIL!="NULL")%>%summarise(Total=n())%>%arrange(desc(Total)))
}
q12<-estado_civil(datos_violencia)
#Muestra de Valores:
q12
```

```{r}
#13 Nos muestra la todas las semillas que cumplan o sean mayor al valor del Area requerida.

tipo_semilla<-function(df,area)
{
  dv<-df%>%group_by(Tipo,Area)%>%filter(Area>area)%>%select(c(1,8))
  return(dv)
}
q13<-tipo_semilla(semillas,8)
#Muestra de Valores:
q13
```

```{r}
#14 Nos muestra el promedio de las edades de las personas denunciantes.

promedio_Edad<-function(df)
{
  return(mean(df$EDAD))
}
q14<-promedio_Edad(datos_violencia)
#Muestra de Valores:
q14
```

```{r}
#15) Nos muestra el porcentaje de denuncias encontradas en el dataset filtrado por la edad y tipo de denuncia, el calculo del porcentaje se obtiene dividiendo el total de casos entre la cantidad de denuncias. Nos muestra el porcentaje de personas de 28 años que denuncian.

porcentaje_Edades<-function(df,edad,todos) # PORCENTAJE EN GENERAL CON TODO EL DATASET
{
  q15<-df%>%group_by(Edad=df$EDAD)%>%summarise(total=n())%>%arrange(desc(total))
  q15$Porcentaje=(q15$total/NROW(df))*100
  if(todos==FALSE)
  {
  return(q15<-q15%>%filter(Edad==edad))
  }
  else
  {
   return(q15) 
  }
}

q15<-porcentaje_Edades(datos_violencia,18,TRUE)
#Muestra de Valores:
q15
```


```{r}
#16)Nos muestra la cantidad de casos registrados filtrados por edad y el tipo de denuncia realizado.

porc_tip_denuncia<-function(df,edad,denuncia_tipo)
{
  q<-df%>%group_by(EDAD,TIPO_DENUNCIA)%>%filter(EDAD==edad & TIPO_DENUNCIA==denuncia_tipo)%>%summarise(total=n())%>%arrange(desc(total))
  da<-df%>%group_by(TIPO_DENUNCIA)%>%filter(TIPO_DENUNCIA==denuncia_tipo)%>%summarise(tot=n())
  q$Porcentaje=(q$total/da$tot)*100  
  return (q)
}
q16<-porc_tip_denuncia(datos_violencia,18,'DENUNCIA')
#Muestra de Valores:
q16
```

```{r}
#17)Cantidad de casos registrados filtrado por edad y el tipo de denuncia, donde se nos muestra el porcentaje de denuncias por cada tipo de denuncia que realizan las personas por su edad.

porc_tip_edad<-function(df,edad)
{
  da<-df%>%group_by(EDAD,TIPO_DENUNCIA)%>%filter(EDAD==edad)%>%summarise(tot=n())
  dto<-df%>%group_by(EDAD)%>%filter(EDAD==edad)%>%summarise(tot=n())
  da$tot=(da$tot/dto$tot)*100
  return (da)
}
q17<-porc_tip_edad(datos_violencia,18)
#Muestra de Valores:
q17
```

```{r}
# 18) Nos muestra los datos relevantes de la columna, buscando por una fecha especifica de búsqueda.

datosobtenidos_porfecha<-function(df,fecha)
{
  return(df%>%filter(FECHA_HORA_HECHO==fecha))
}
q18<-datosobtenidos_porfecha(datos_violencia,'2016-12-31')
#Muestra de Valores:
q18[,c(8,7,15,29,30,20)]

```

```{r}
# 19) Deseamos buscar las personas hechos por la modalidad de Violencia física y psicológica ocurridos en Lima provenientes de chile que sean del género masculino.

query19<-function(modalidad,departamento,pais,tipo_denuncia,genero){
  return(datos_violencia%>%filter(datos_violencia$MODALIDAD==modalidad & datos_violencia$DPTO_CIA==departamento & datos_violencia$pais_natal==pais & datos_violencia$TIPO_DENUNCIA==tipo_denuncia &datos_violencia$SEXO==genero))
}
q19<-query19("VIOLENCIA FISICA Y PSICOLOGICA","LIMA","CHILE","DENUNCIA","M")
q19[,c(3,29,30,33,35)]
```

```{r}
# q20) En este query podemos ver la cantidad de casos resueltos y por resolver agrupados por la provincia en la que se realizó la denuncia. Los casos por resolver representan un porcentaje mucho menor, esto es una señal positiva.

q20<-datos_violencia%>%group_by(datos_violencia$PROV_CIA,datos_violencia$ESTADO_DEN)%>%summarise(Total=n())%>%arrange(desc(Total))
q20
```



```{r}
# grafico 1) Nos muestra la proporción que existe de los diferentes tipos de modalidades de agresión que son registrados en las diferents comisarías alrededor del Perú. De estas las más denunciadas son las modalidades de Violencia Física y psicológica, Violencia Física y Violencia Física psicológica
qplot(x=reorder(Modalidad,Cantidad_Casos),y=Cantidad_Casos,data = q2,geom = "col")+aes(fill= Modalidad)

```

```{r}
# grafico 2) En este gráfico podemos observar el total de denuncias realizadas en los diferents departamento del Perú. Con esto podemos ver que Lima tiene una mayor cantidad de denuncias y sobrepasa a los demás departamentos por un amplio margen, teniendo una diferencia de mas de 40000 con el segundo lugar que es Arequipa"
qplot(x=Total,y=reorder(DPTO_CIA,Total),data = q3,geom = "col")+aes(fill= DPTO_CIA)+ylab("")
```

```{r}
# grafico 3) En el gráfico podemos observar el estado de las personas que han sido registradas en las diferentes denuncias policiales, aquí vemos que de las cinco el denunciado y denunciante son las dos más sobresalientes, un resultado esperado tomando el cuenta las definiciones de las otras tres opciones. Los denunciados y denunciantes ocupan el 95% de las denuncias realizadas.
qplot(x=reorder(SIT_PERSONA,Total),y=Total,data = q4%>%slice(1:5),geom = "col")+aes(fill= SIT_PERSONA)
# comprobar el porcentaje
#(q4$Total[2]+q4$Total[1])/sum(q4$Total)

```

```{r}
# grafico 4) En este gráfico podemos observar los cuatro países más involucrados con las denuncias después del Perú. Incluso en el año que se realizó el informe los inmigrantes del país de Venezuela ya empiezan a tener un impacto muchas veces negativo para la seguridad, pero siendo seguidos por los colombianos. Se ignora al Perú en este gráfico ya que lo altera de forma que no se pueden apreciar los demás países.
qplot(x=reorder(pais_natal,Total)  ,y=Total,data = q5%>%slice(2:5),geom = "col")+aes(fill= pais_natal)
```

```{r}
# grafico 5) En el gráfico podemos ver un rango de las edades de las personas relacionadas a las denuncias, se observa que el pico de casos se genera ente los 25 a 30 años, edad común en familias jóvenes.
qplot(x=EDAD   ,y=Total,data = q6,geom = "line")+aes(fill= EDAD )
```

```{r}
# grafico 6) Primer gráfico relacionado al género de las personas relacionadas a las denuncias, si bien parece parejo se nota que el genero femenino tiene mayor cantidad de casos.
 ggplot(data = q7, aes(x="", y=q7$Total, fill=SEXO)) +
   geom_bar(stat="identity", width=1) +
  coord_polar("y", start=0)+theme_void()

```

```{r}
# grafico 7) Gráfico relacionado al gráfico N°2, como observamos en ese Lima era el departamento con mayor número de casos, en este gráfico observamos los 5 distritos con mayor cantidad de casos. En los primero lugares predominan  zonas que son consideradas muy peligrosas en Lima y el Callao.
qplot(x=reorder( DIST_CIA,Total)   ,y=Total,data = q8,geom = "col")+aes(fill= DIST_CIA )

```

```{r}
# grafico 8) En el gráfico se aprecia la proporción del destino de la mayoría de los casos denunciados, el juzgado de familia es el número uno siendo el destino de casi tres cuartas partes de los casos totales.
ggplot(data = q9, aes(x="", y= Total, fill= DERIVADA_FISCALIA)) +
  geom_bar(stat="identity", width=1,color="white") +
  coord_polar("y", start=0)+theme_void()
```

```{r}
# grafico 9) Gráfico relevante con el gráfico 6, en este podemos observar que el porcentaje previo relacionado a los denunciantes y denunciados está fuertemente polarizado, siendo los hombres los denunciados y las mujeres las denunciantes. Esto demuestra que aún vivimos en una sociedad muy insegura para el género femenino.
qplot(x=SIT_PERSONA  ,y=Total,data = q10,geom = "col")+aes(fill= SEXO)

```

```{r}
# grafico 10) Grafico del numero de casos ordenados por mes del año. Podemos ver que mientras el año acaba el númejor de casos aumenta, esto puede deberse a diferentes factores como el fin del año o las celebraciones navideñas.
qplot(x= reorder(MES,Total)  ,y=Total,data = q11,geom = "col")+aes(fill= MES)+theme_minimal()

```

```{r}
# grafico 11) Relación de estado civil con la cantidad de denuncias. Las personas viudas presentan menos casos mientras que los Solteros y Casados suman mas de la mitad.
qplot(x=reorder( EST_CIVIL,Total),y=Total,data = q12)+aes(fill= EST_CIVIL ) +
  geom_point(size=4, color="#aaaaaa") +
  theme_minimal()+
  theme(legend.position = "none") +
  geom_text(aes(label=q12$Total),hjust=0, vjust=0)+
  xlab("Estado Civil")
```

```{r}
# grafico 12) Podemos ver gráficos de caja donde se aprecia los valores del area de las semillas dependiendo de su tipo, el tipo dos o Rosa tiene el area promedio mas grande.
qplot(x=reorder(Tipo,Area)   ,y=Area,data = q13,geom = "boxplot")+theme_classic()+xlab(label = "")+aes(group= Tipo)

```

```{r}
# grafico 13) Grafico que nos muestra el porcentaje de cada tipo de denuncias hechas por personas de 18 años de edad, elegimos esta edad ya que aquí empieza la mayoría de edad en el Perú. El tipo de denuncia mas popular fue "Denuncia".
ggplot(data = q17, aes(x="", y= tot, fill= TIPO_DENUNCIA)) +
  geom_bar(stat="identity", width=1,color="white") +
  coord_polar("y", start=0)+theme_void()+
   geom_text(aes(label = paste(round(tot, digits = 2)
, "%"), x = 1.3),
            position = position_stack(vjust = 0.5))

```

```{r}
# grafico 14) Aplicamos el kmean a nuestro datos de las semillas, elegimos que se agrupen en 3 ya que sabemos de antemano que es el numero de tipos de semillas.
semillas1<-semillas
semi_kmean<-kmeans(x = semillas1,centers = 3,iter.max = 10,nstart = 30)
semillas1 <- semillas1 %>% mutate(cluster = semi_kmean$cluster)
semillas1 <- semillas1 %>% mutate(cluster = as.factor(cluster),
                                  #grupo   = as.factor(grupo))
                                  grupo   = 3)
gm1<-ggplot(data = semillas1, 
            aes(x = Perimetro,
                y =Coeficiente_de_Asimetria,
                color =cluster)) +
  geom_text(aes(label = cluster), size = 5) +
  theme_bw() +
          theme(legend.position = "none")+xlab("Perimetro")+ylab("Coeficiente de asimetria")
gm1
```

```{r}
# grafico 15) Aplicación de la regresión lineal, usamos el ancho y largo para este caso. Se puede observar que ambos valores son directamente proporcionales.

gm2<-ggplot(data =semillas1, aes(largo,ancho))+ geom_point() +   geom_smooth(method = "lm")
gm2

```

```{r}
# grafico 16) Regresión multivariada, en este caso Buscamos hallar el área de las semillas con respecto a su largo ancho y perímetro. Estos valores los elejimos ya que para calcular el area de un objeto estas serían las variables ideales. 
 
regre_multi_semillas<-lm(data = semillas,semillas$Area~semillas$Perimetro+semillas$largo+semillas$ancho)
gm4<-ggplot(data=regre_multi_semillas,aes(x = regre_multi_semillas$fitted.values,y = regre_multi_semillas$residuals))+
            geom_point() + geom_smooth()
  layout(matrix(c(1,2,3,4),2,2))
  plot(regre_multi_semillas)


gm4
```

```{r}
# grafico 17) Usamos el Knn para predecir los tipos de semillas. Se puede apreciar una diferencia en los etiquetados con respecto al kmeans, ya que algunas semillas son afectadas por sus vecinos y no por las operaciones del kmeans
idxs <- sample(1:nrow(semillas),as.integer(0.7*nrow(semillas)))
trainSemillas <- semillas[idxs,]
testSemillas <- semillas[-idxs,]
        
nn3 <- kNN(Tipo ~ .,trainSemillas,testSemillas,norm=FALSE,k=3)
nn31 <- as.numeric(levels(nn3))[nn3]
gm7<-testSemillas
gm7$knn<-nn31

ggplot(data = gm7, 
            aes(x = Perimetro,
                y =Coeficiente_de_Asimetria,
                color =knn)) +
  geom_text(aes(label = knn), size = 5) +
  theme_bw() +
          theme(legend.position = "none")+xlab("Perimetro")+ylab("Coeficiente de asimetria")


```

